Alert Component
palmetto/palmetto-components pull request #213
Opened 2020-09-04 16:29 UTC by juanfabrega

PR addressing this component: https://github.com/palmetto/palmetto-components/issues/21

Apologies, I moved on this without looking at the MVP props that are in the issue, but I believe the functionality is all there, with a few more options. The one exception being the `autoClose` on a timer, but that should be feasible without too much effort.

2020-09-04 17:58 UTC, nathanyoung commented
I'd like to keep the font color standard across all alerts. I started a figma file way back that looks like this:

<img width="731" alt="Screen Shot 2020-09-04 at 10 57 15 AM" src="https://user-images.githubusercontent.com/1447339/92271891-6df0df80-ee9d-11ea-8e6f-819c2028e172.png">

2020-09-04 17:59 UTC, juanfabrega commented
> I'd like to keep the font color standard across all alerts. I started a figma file way back that looks like this:
> 
> <img alt="Screen Shot 2020-09-04 at 10 57 15 AM" width="731" src="https://user-images.githubusercontent.com/1447339/92271891-6df0df80-ee9d-11ea-8e6f-819c2028e172.png">

Cool, I'm on it!

2020-09-05 00:09 UTC, juanfabrega commented
@nathanyoung this is ready for another onceover.

2020-09-08 23:08 UTC, nathanyoung commented on src/components/Alert/Alert.tsx
> +            {message && <span>{message}</span>}
why a `span` and not a `p` or `div`?

2020-09-08 23:09 UTC, nathanyoung commented on src/components/Alert/Alert.module.scss
> +    margin-right: var(--size-spacing-sm);
should we define a new alert token for this instead of using the spacing token directly?

2020-09-08 23:10 UTC, nathanyoung commented on src/components/Alert/Alert.module.scss
> +      margin-right: var(--size-spacing-sm);
should we define a new alert token for this instead of using the spacing token directly?

2020-09-08 23:10 UTC, nathanyoung commented on src/components/Alert/Alert.module.scss
> +    margin-bottom: var(--size-spacing-2xs);
should we define a new alert token for this instead of using the spacing token directly?

2020-09-09 05:23 UTC, nathanyoung requested changes
<img width="607" alt="Screen Shot 2020-09-08 at 10 22 11 PM" src="https://user-images.githubusercontent.com/1447339/92557741-c0c1f280-f221-11ea-8856-61465ae474bd.png">

Can we color the icons so that they correspond with the type?

font-color-secondary for info
font-color-danger for danger,
font-color-success for success, etc...

2020-09-09 05:37 UTC, nathanyoung commented on src/components/Alert/Alert.tsx
> +          <FontAwesomeIcon
Should be wrapped in a button. It's not keyboard focusable.

2020-09-09 21:11 UTC, nathanyoung requested changes

2020-09-09 21:11 UTC, nathanyoung commented on src/components/Alert/Alert.tsx
> +          <FontAwesomeIcon
The <FontAwesomeIcon /> needs to be wrapped in `<button>` too and the onClick handler moved. 

`role="button"` doesn't allow it to be focusable.

2020-09-10 00:30 UTC, merged