Link
palmetto/palmetto-components pull request #235
Opened 2020-09-15 20:12 UTC by juanfabrega

Implementation of a text link component.

It can be made to render either a react-router `Link` or a standard anchor tag based on whether the user passes a `href` or a `to` attribute.

2020-09-15 21:51 UTC, nathanyoung requested changes
<img width="1003" alt="Screen Shot 2020-09-15 at 2 49 58 PM" src="https://user-images.githubusercontent.com/1447339/93268841-c90ab800-f762-11ea-92f8-020d531520fe.png">

I see `className` as a prop in TextLinkBaseProps but it's not showing up as a prop in the prop table documentation

2020-09-15 21:53 UTC, nathanyoung commented
`href` is also not displayed in the prop table

2020-09-16 12:09 UTC, juanfabrega commented
@nathanyoung I fixed the props issues. Our typescript docgen loader does some not so clear things when extending interfaces. See here: https://github.com/strothj/react-docgen-typescript-loader/issues/47

But with the new structure all 4 of the props we care about are there and the `...rest` should also be type safe.

2020-09-16 16:54 UTC, nathanyoung approved these changes

2020-09-16 16:54 UTC, merged