Responsive box
palmetto/palmetto-components pull request #257
Opened 2020-10-02 21:27 UTC by juanfabrega

2020-10-07 23:44 UTC, nathanyoung requested changes

2020-10-07 23:44 UTC, nathanyoung commented on src/components/Box/Box.tsx
> +  alignItems?: CssAlign | ResponsiveGeneric;
story needs to be updated to reflect new prop name and possible values

2020-10-07 23:44 UTC, nathanyoung commented on src/components/Box/Box.tsx
> +  alignContent?: CssAlignContent | ResponsiveGeneric;
story needs to be updated to reflect new prop name and possible values

2020-10-07 23:44 UTC, nathanyoung commented on src/components/Box/Box.tsx
> +  alignSelf?: CssAlign | ResponsiveGeneric;
story needs to be updated to reflect new prop name and possible values

2020-10-07 23:44 UTC, nathanyoung commented on src/components/Box/Box.tsx
> +  justifyContent?: CssJustifyContent | ResponsiveGeneric;
story needs to be updated to reflect new prop name and possible values

2020-10-08 15:34 UTC, juanfabrega commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add responsive capability to props in the Box component](https://trello.com/c/CDvpC92G/232-add-responsive-capability-to-props-in-the-box-component)

2020-10-08 15:34 UTC, juanfabrega commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add responsive capability to props in the Box component](https://trello.com/c/CDvpC92G/232-add-responsive-capability-to-props-in-the-box-component)

2020-10-08 15:34 UTC, juanfabrega commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add responsive capability to props in the Box component](https://trello.com/c/CDvpC92G/232-add-responsive-capability-to-props-in-the-box-component)

2020-10-08 17:59 UTC, nathanyoung approved these changes

2020-10-08 18:00 UTC, merged

2020-10-08 18:00 UTC, nathanyoung commented
https://github.com/palmetto/palmetto-components/pull/257

2020-10-08 18:01 UTC, nathanyoung commented
https://github.com/palmetto/palmetto-components/issues/263