docs: Alert component documentation re-organization
palmetto/palmetto-components pull request #397
Opened 2021-02-04 22:23 UTC by osbornedesign

![image](https://user-images.githubusercontent.com/15643874/106962751-98c1b700-670d-11eb-8838-0cd05e65d18f.png)

2021-02-04 23:11 UTC, nathanyoung requested changes

2021-02-04 23:11 UTC, nathanyoung commented on src/components/Alert/Alert.VisualTests.stories.tsx
> +export const WithMessageWithIcon = Template.bind({});
You can add a more human readable storyname like this for each component:

`WithMessageWithIcon.storyName = 'With Message, Icon";`

https://storybook.js.org/docs/react/api/csf#named-story-exports

2021-02-04 23:11 UTC, nathanyoung commented on src/components/Alert/Alert.VisualTests.stories.tsx
> +
```suggestion
WithMessageWithIconWithClosable.storyName = "With Message, Icon, Closable"
```

2021-02-04 23:11 UTC, nathanyoung commented on src/components/Alert/Alert.Playground.stories.tsx
> +const alertVariants = [
Use the `AlertVariants` defined in Alert.tsx instead of creating the same thing here.

2021-02-05 20:47 UTC, juanfabrega approved these changes
This is some good work!

2021-02-05 20:48 UTC, nathanyoung approved these changes

2021-02-05 20:48 UTC, merged