fix(Button): add white button variant
palmetto/palmetto-components pull request #598
Opened 2021-09-15 18:29 UTC by mtblanton

# Github Issue or Trello Card
This PR addresses this issue: #597

# What type of change is this?
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updating documentation.
- [ ] Updating deployment/build pipeline.
- [ ] Updating Project Dependencies
- [ ] Improving or adding to Test Coverage

# Completeness Checklist

- [x] TESTS: My changes maintain the baseline required test coverage, as specified by code climate analysis.
- [x] DOCS: All new component work is covered in that component's `Overview` docs.
- [x] DOCS: All new component work is covered in a component `Playground`.
- [x] DOCS: All new visual changes or options are covered under relevant components' `VisualTests`.
- [x] My code has no linting or typescript compile warnings.
- [x] My work is tied to a Github issue and satisfies the acceptance criteria (if applicable) of the corresponding issue.

# Quality Checklist:

- [ ] My code follows the style guidelines of this project - possibly not due to needing a transparent color for the background
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# UI Checklist
- [x] I have conducted visual UAT on my changes/features.
- [x] My solution works well on desktop, tablet, and mobile browsers.

2021-09-15 18:31 UTC, mtblanton commented on src/components/Button/Button.Overview.stories.mdx
> +      <Box background="primary" padding="2xs">
I added this background so the button is visible, if you all have a better solution for this please LMK!

2021-09-15 18:45 UTC, juanfabrega commented
@nathanyoung I think you should probably review this one from a visual standpoint.

2021-09-15 18:46 UTC, nathanyoung requested changes
Please add the white variants to our "Visual Regression Tests" stories. 

https://github.com/palmetto/palmetto-components/blob/main/src/components/Button/Button.VisualTests.stories.tsx

This will render the white variant with every prop combination

2021-09-15 19:00 UTC, nathanyoung commented
![](https://github.trello.services/images/mini-trello-icon.png) [Button - "white" variant](https://trello.com/c/ibEymAf1/917-button-white-variant)

2021-09-16 15:40 UTC, nathanyoung commented on src/styles/variables/buttons.scss
> +  --button-background-hover-color-white: var(--color-brand-grey-200);
```suggestion
  --button-background-hover-color-white: var(--color-brand-grey-100);
```

2021-09-21 15:38 UTC, nathanyoung commented
@mtblanton This PR looks good, but we're going to hold on merging this for now until the design team has had a chance to think about what we really want to do here.

2022-02-15 19:20 UTC, nathanyoung commented
> 

Let me bring this up with the team in standup tomorrow

2022-02-16 22:28 UTC, nathanyoung approved these changes

2022-02-16 22:29 UTC, merged