Responsive radio
palmetto/palmetto-components pull request #607
Opened 2021-09-30 20:50 UTC by juanfabrega

# Github Issue or Trello Card
This PR addresses this issue: https://github.com/palmetto/palmetto-components/issues/437

# What type of change is this?
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updating documentation.
- [ ] Updating deployment/build pipeline.
- [ ] Updating Project Dependencies
- [ ] Improving or adding to Test Coverage

# Completeness Checklist

- [X] TESTS: My changes maintain the baseline required test coverage, as specified by code climate analysis.
- [X] DOCS: All new component work is covered in that component's `Overview` docs.
- [X] DOCS: All new component work is covered in a component `Playground`.
- [ ] DOCS: All new visual changes or options are covered under relevant components' `VisualTests`.
- [X] My code has no linting or typescript compile warnings.
- [X] My work is tied to a Github issue and satisfies the acceptance criteria (if applicable) of the corresponding issue.

# Quality Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

# UI Checklist
- [X] I have conducted visual UAT on my changes/features.
- [X] My solution works well on desktop, tablet, and mobile browsers.

2021-10-01 14:56 UTC, nathanyoung requested changes
https://user-images.githubusercontent.com/1447339/135641631-8c2ad99d-a97c-4fc9-949e-d087ca47130e.mov

I think this is caused because the input ids aren't unique.

2021-10-01 14:56 UTC, nathanyoung commented on src/components/RadioGroup/RadioGroup.Overview.stories.mdx
> +            value={state.lg}
```suggestion
            value={state.responsive}
```

2021-10-04 14:46 UTC, juanfabrega commented
@nathanyoung can you still replicate the issue with mixed state across inputs? I am unable to replicate it at the moment.

2021-10-04 15:28 UTC, nathanyoung commented
> @nathanyoung can you still replicate the issue with mixed state across inputs? I am unable to replicate it at the moment.

yes, it's because the ids are not unique. There are accessibility warnings too. 

<img width="489" alt="Screen Shot 2021-10-04 at 8 27 21 AM" src="https://user-images.githubusercontent.com/1447339/135879421-395df7c0-88b7-4dc2-ba1e-fe9d0ab086c0.png">

2021-10-04 17:21 UTC, nathanyoung commented
![](https://github.trello.services/images/mini-trello-icon.png) [Responsive sizes design and implementation for RadioGroup](https://trello.com/c/TYgQyo8r/737-responsive-sizes-design-and-implementation-for-radiogroup)

2021-10-04 17:21 UTC, nathanyoung approved these changes

2021-10-04 17:21 UTC, merged